# Generated by Django 4.1.5 on 2023-05-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_manager_AI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
